version: "3.8"

services:
  micafe-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CACHE_TTL_MS=300000
      - SCRAPING_TIMEOUT_MS=10000
      - MAX_RETRIES=3
      - RETRY_DELAY_MS=1000
      - FEDERACION_CAFETEROS_URL=https://federaciondecafeteros.org
      - LOG_LEVEL=info
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/status', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - micafe-api
    restart: unless-stopped
    profiles:
      - production
